# Generated by Django 2.2.14 on 2022-05-18 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220517_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fundacion',
            fields=[
                ('idFundacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('telefono', models.IntegerField(blank=True)),
                ('estrato', models.IntegerField(blank=True)),
                ('descripcion', models.TextField(blank=True)),
                ('cc_admid', models.CharField(blank=True, max_length=25)),
                ('ciudad', models.CharField(blank=True, max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=20)),
                ('departamento', models.TextField()),
                ('codigo_nit', models.CharField(blank=True, max_length=20)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Administrador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
