# Generated by Django 2.2.14 on 2022-05-31 20:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220518_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fundaciones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='fundacion',
            name='nombre_admin',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
