# Generated by Django 2.2.14 on 2022-05-31 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220531_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='especificaciones_cuenta',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='cuenta_ahorros',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
