# Generated by Django 2.2.14 on 2022-06-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220531_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='item2',
            name='busca_intercambio',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
